apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  type: {{ .Values.database.service.type }}
  selector:
    app: database
  ports:
    - protocol: TCP
      port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}